In [13]:
from sklearn.datasets import fetch_openml
import sklearn

mnist = fetch_openml('mnist_784', version=1)


In [14]:
import numpy as np

np.array(mnist['target'])
X, y = mnist["data"], mnist["target"].astype(np.uint8)
y = y.sort_values()
X.reindex(index=y.index)
X.sort_index


<bound method DataFrame.sort_index of        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0  

In [15]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [16]:
print(y_train.unique())
print(y_test.unique())

[0 1 2 3 4 5 6 7]
[7 8 9]


In [17]:
from sklearn.model_selection import train_test_split
import pickle
from sklearn.model_selection import cross_val_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
print(y_train.unique())
print(y_test.unique())
print(y_test.size / (y_train.size + y_test.size))

[6 9 1 4 0 2 8 3 5 7]
[6 5 4 1 3 0 8 2 9 7]
0.2


In [19]:
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)

In [20]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)
acc = [sgd_clf.score(X_train, y_train_0), sgd_clf.score(X_test,y_test_0)]
with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump(acc, f)

In [21]:
score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy", n_jobs=-1)
with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(score, f)

In [22]:
sgd_multiclass_clf = SGDClassifier(random_state=42,n_jobs=-1)
sgd_multiclass_clf.fit(X_train, y_train)
y_train_pred = sgd_multiclass_clf.predict(X_train)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_train, y_train_pred)
with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(confusion_matrix, f)